name: CI

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3
        with:
          install: false
      - run: pnpm install --frozen-lockfile --ignore-scripts
      - run: pnpm biome:ci
      - run: pnpm check:theme
      - run: pnpm package
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: srcery-vsix
          path: srcery-colors-*.vsix
          if-no-files-found: error
