name: CI

on:
  push:
    branches: [master]
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3
        with:
          install: false
      - run: pnpm install --frozen-lockfile --ignore-scripts
      - run: pnpm biome:ci
      - run: pnpm check:theme
      - run: pnpm package
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: srcery-vsix
          path: srcery-colors-*.vsix
          if-no-files-found: error
